#! /usr/bin/env ruby

require '/usr/bin/frame.rb'
require '/usr/bin/neuron_generation.rb'
require '/usr/bin/connect.rb'

def input
  write_neuron "NetworkIn"
    yield
  write_neuron "EndNetworkIn"
end

def output
  write_neuron "NetworkOut"
    yield
  write_neuron "EndNetworkOut"
end

unless ARGV[0].nil?
  load ARGV[0]
else
  load 'main.rb'
end

File.open "schema.txt", "w" do |file|
  file.write "Name: Prodigy\n"
  file.write "NumberOfNeurons: #{Neuron.count}\n"
  file.write "NumberOfDendrites: #{Connection.count_max_dendrites}\n"
  file.write "BasePort: 3000\n"
end

File.open "net.txt", "w" do |file|
  file.write @neuron_data
  file.write "\n"
  file.write @connection_data
end
