#Lexicon symbols
alien '_Lshoulders', 'input', [0, 0]
alien '_Lupperbody', 'input', [1, 1]
alien '_Ltriceps', 'input', [2, 2]
alien '_Lcore', 'input', [3, 3]
alien '_Labs', 'input', [4, 4]
alien '_Lstronger-bigger', 'input', [5, 5]
alien '_Lmedicine-ball', 'input', [6, 6]
alien '_Lweightlifting', 'input', [7, 7]
alien '_Lplyo-ball', 'input', [8, 8]
alien '_Lbarbell', 'input', [9, 9]
alien '_Lcable-machine', 'input', [10, 10]
alien '_Ldumbbells', 'input', [11, 11]
alien '_LSince_we_worked_on_your0', 'input', [12, 12]
alien '_Lshoulders1', 'input', [13, 13]
alien '_Land2', 'input', [14, 14]
alien '_Ltriceps3', 'input', [15, 15]
alien '_Lfor_your_last_workout_,_and_your_goal_is_to4', 'input', [16, 16]
alien '_Lstronger-bigger5', 'input', [17, 17]
alien '_L,_I_wanted_to_focus_on_your6', 'input', [18, 18]
alien '_Lbiceps7', 'input', [19, 19]
alien '_Land8', 'input', [20, 20]
alien '_Lchest9', 'input', [21, 21]
alien '_L.11', 'input', [22, 22]
alien '_Llegs', 'input', [23, 23]
alien '_Lagility', 'input', [24, 24]
alien '_Lconditioning', 'input', [25, 25]
alien '_Llowerbody', 'input', [26, 26]
alien '_Lagility5', 'input', [27, 27]
alien '_Lchest', 'input', [28, 28]
alien '_Lbiceps', 'input', [29, 29]
alien '_Lgetting-cut', 'input', [30, 30]
alien '_Lbench', 'input', [31, 31]
alien '_Lchest1', 'input', [32, 32]
alien '_Lbiceps3', 'input', [33, 33]
alien '_Lgetting-cut5', 'input', [34, 34]
alien '_Llegs7', 'input', [35, 35]
alien '_Lback9', 'input', [36, 36]
alien '_Lpull-up-bar', 'input', [37, 37]
alien '_Lchest7', 'input', [38, 38]
alien '_Lbiceps9', 'input', [39, 39]
alien '_Ljumping', 'input', [40, 40]
alien '_Lback', 'input', [41, 41]
alien '_Loverall-fitness', 'input', [42, 42]
alien '_Ldecline-bench', 'input', [43, 43]
alien '_Lrun-faster', 'input', [44, 44]
alien '_Lrunning', 'input', [45, 45]
alien '_Lsprinting', 'input', [46, 46]
alien '_Llegs1', 'input', [47, 47]
alien '_Lback3', 'input', [48, 48]
alien '_Loverall-fitness5', 'input', [49, 49]
alien '_Lshoulders7', 'input', [50, 50]
alien '_Ltriceps9', 'input', [51, 51]
alien '_Llosing-weight', 'input', [52, 52]
alien '_Llosing-weight5', 'input', [53, 53]
alien '_Lbiceps1', 'input', [54, 54]
alien '_Lchest3', 'input', [55, 55]
alien '_Lgetting-tone', 'input', [56, 56]
alien '_Lgetting-tone5', 'input', [57, 57]
alien '_Ljump-higher', 'input', [58, 58]
alien '_Lincline-bench', 'input', [59, 59]
alien '_Lcurl-bar', 'input', [60, 60]
alien '_Linside', 'input', [61, 61]
#Leixcon symbol names in a useful array
@lexicon_symbols = ["_Lshoulders", "_Lupperbody", "_Ltriceps", "_Lcore", "_Labs", "_Lstronger-bigger", "_Lmedicine-ball", "_Lweightlifting", "_Lplyo-ball", "_Lbarbell", "_Lcable-machine", "_Ldumbbells", "_LSince_we_worked_on_your0", "_Lshoulders1", "_Land2", "_Ltriceps3", "_Lfor_your_last_workout_,_and_your_goal_is_to4", "_Lstronger-bigger5", "_L,_I_wanted_to_focus_on_your6", "_Lbiceps7", "_Land8", "_Lchest9", "_L.11", "_Llegs", "_Lagility", "_Lconditioning", "_Llowerbody", "_Lagility5", "_Lchest", "_Lbiceps", "_Lgetting-cut", "_Lbench", "_Lchest1", "_Lbiceps3", "_Lgetting-cut5", "_Llegs7", "_Lback9", "_Lpull-up-bar", "_Lchest7", "_Lbiceps9", "_Ljumping", "_Lback", "_Loverall-fitness", "_Ldecline-bench", "_Lrun-faster", "_Lrunning", "_Lsprinting", "_Llegs1", "_Lback3", "_Loverall-fitness5", "_Lshoulders7", "_Ltriceps9", "_Llosing-weight", "_Llosing-weight5", "_Lbiceps1", "_Lchest3", "_Lgetting-tone", "_Lgetting-tone5", "_Ljump-higher", "_Lincline-bench", "_Lcurl-bar", "_Linside"]
#Number of words in the lexicon

LEXICON_COUNT = 62
