#! /usr/bin/env ruby

require 'socket'

#Defaults
ip = "127.0.0.1"
port = "3000"

if ARGV.count == 3
  ip = ARGV[0]
  port = ARGV[1]
  vector = ARGV[2]
elsif ARGV.count == 2
  port = ARGV[0]
  vector = ARGV[1]
elsif ARGV.count == 1
  vector = ARGV[0]
else
  puts "Either [ip port vector], [port vector], or [vector]"
  exit
end

s = UDPSocket.new
s.send(vector, 0, ip, port)
